name: Continous Delivery

on:
  push:
    branches:
      - main

permissions:
  contents: read
  actions: read
  pull-requests: write
  security-events: write
  statuses: write


jobs:
  cd-linting:
    name: Generate cache for Linting
    uses: DigitalFemsa-Genesys/genesys-ci-cd-workflows/.github/workflows/terraform-linting.yaml@v1
    with:
      runs-on-json: ${{ vars.GSYS_RUNS_ON_JSON != '' && vars.GSYS_RUNS_ON_JSON || '"ubuntu-latest"' }}
      propagate-failure: true
      access-private-modules: true
    secrets:
      PRIVATE_MODULES_TOKEN: ${{ secrets.GLOBAL_REPO_TOKEN }}